### PR TITLE
Refactor torch_ort and ort_moe into their respective directories

### PR DESCRIPTION
**Pull request by jingyanwangms**
Moving torch_ort and ort_moe code including setup.*, tests, docker, docs into respective directory - moving files, update documentations and directory only, no functional code change

### CODE REVIEW

**Comment by askhade** [comment]
Overall the PR looks good to me. Just 1 comment : If you think that having all pipelines together under a single common folder makes sense then it works for me, just change the pipeline names to include torch_ort in the name OR alternatively move the pipelines under torch_ort folder.

**Comment by jingyanwangms** [comment]
> Overall the PR looks good to me. Just 1 comment : If you think that having all pipelines together under a single common folder makes sense then it works for me, just change the pipeline names to include torch_ort in the name OR alternatively move the pipelines under torch_ort folder.

@baijumeswani what do you think? should we either move pipeline files to torch_ort or add torch_ort to some of the tools/ directory/file names?

**Review by baijumeswani — APPROVED** [review]

**Comment by jingyanwangms** [comment]
> > Overall the PR looks good to me. Just 1 comment : If you think that having all pipelines together under a single common folder makes sense then it works for me, just change the pipeline names to include torch_ort in the name OR alternatively move the pipelines under torch_ort folder.
> 
> @baijumeswani what do you think? should we either move pipeline files to torch_ort or add torch_ort to some of the tools/ directory/file names?

updated file names

**Comment by baijumeswani** [comment]
Thanks @jingyanwangms

**Review by baijumeswani — APPROVED** [review]

**Comment by askhade** [comment]
@jingyanwangms : I see you deleted these files:
image
but I dont see the new files with updated names. What am I missing?

**Comment by jingyanwangms** [comment]
> @jingyanwangms : I see you deleted these files: image but I dont see the new files with updated names. What am I missing?

My bad, I didn't add the renamed file. Two files are deleted

**Review by askhade — APPROVED** [review]
LGTM

**Review by devang-ml — APPROVED** [review]

**Pull request merged**
